# Generated by Django 3.1.5 on 2021-01-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210127_1037'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='end',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='start',
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doctorbusyperiod_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doctor.doctorbusyperiod'),
            preserve_default=False,
        ),
    ]
