# Generated by Django 3.1.5 on 2021-01-28 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210126_2326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
