# Generated by Django 3.1.5 on 2021-01-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorBlockedPeriod',
            new_name='DoctorBlockedOffPeriod',
        ),
    ]
