# Generated by Django 3.1.5 on 2021-01-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210127_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbusyperiod',
            name='end',
            field=models.DateTimeField(help_text='End time', verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='doctorbusyperiod',
            name='start',
            field=models.DateTimeField(help_text='Start time', verbose_name='Start'),
        ),
    ]
